components:
- layout_properties: {grid_position: 'JEPAPO,LRUGBG'}
  name: chk_task
  properties: {}
  type: form:dep_lin1x4oec0ytd:_Components.Checkbox
- layout_properties: {grid_position: 'JEPAPO,QGBQHO'}
  name: txt_datetime
  properties:
    spacing:
      margin: ['4', null, '4', null]
      padding: ['8', null, '8', null]
  type: form:dep_lin1x4oec0ytd:_Components.Text
- layout_properties: {grid_position: 'JEPAPO,YPTXFN'}
  name: lnk_delete
  properties:
    align: center
    bold: true
    icon: mi:close
    icon_color: red
    icon_size: 20
    spacing:
      margin: ['4', null, '0', null]
      padding: ['8', null, '8', null]
    tooltip: Delete
    underline: false
  type: form:dep_lin1x4oec0ytd:_Components.Link
container:
  properties: {col_spacing: small, col_widths: '{"LRUGBG":25,"QGBQHO":30,"YPTXFN":5}'}
  type: ColumnPanel
is_package: true
